import 'dart:convert';

class Country {
  final int id;
  final String name;

  Country({required this.id, required this.name});

  factory Country.fromJson(Map<String, dynamic> json) {
    return Country(id: json['id'], name: json['name']);
  }

  Map<String, dynamic> toJson() {
    return {'id': id, 'name': name};
  }

  static List<Country> fromJsonList(List<dynamic> jsonList) {
    return jsonList.map((json) => Country.fromJson(json)).toList();
  }

  static String encode(List<Country> assets) =>
      json.encode(assets.map((asset) => asset.toJson()).toList());

  static List<Country> decode(String assets) =>
      (json.decode(assets) as List<dynamic>)
          .map<Country>((item) => Country.fromJson(item))
          .toList();
}

final List<Country> countries = [
  Country(id: 1, name: 'Afghanistan'),
  Country(id: 2, name: 'Albania'),
  Country(id: 3, name: 'Algeria'),
  Country(id: 4, name: 'Andorra'),
  Country(id: 5, name: 'Angola'),
  Country(id: 6, name: 'Antigua and Barbuda'),
  Country(id: 7, name: 'Argentina'),
  Country(id: 8, name: 'Armenia'),
  Country(id: 9, name: 'Australia'),
  Country(id: 10, name: 'Austria'),
  Country(id: 11, name: 'Azerbaijan'),
  Country(id: 12, name: 'Bahamas'),
  Country(id: 13, name: 'Bahrain'),
  Country(id: 14, name: 'Bangladesh'),
  Country(id: 15, name: 'Barbados'),
  Country(id: 16, name: 'Belarus'),
  Country(id: 17, name: 'Belgium'),
  Country(id: 18, name: 'Belize'),
  Country(id: 19, name: 'Benin'),
  Country(id: 20, name: 'Bhutan'),
  Country(id: 21, name: 'Bolivia'),
  Country(id: 22, name: 'Bosnia and Herzegovina'),
  Country(id: 23, name: 'Botswana'),
  Country(id: 24, name: 'Brazil'),
  Country(id: 25, name: 'Brunei'),
  Country(id: 26, name: 'Bulgaria'),
  Country(id: 27, name: 'Burkina Faso'),
  Country(id: 28, name: 'Burundi'),
  Country(id: 29, name: 'Cambodia'),
  Country(id: 30, name: 'Cameroon'),
  Country(id: 31, name: 'Canada'),
  Country(id: 32, name: 'Central African Republic'),
  Country(id: 33, name: 'Chad'),
  Country(id: 34, name: 'Chile'),
  Country(id: 35, name: 'China'),
  Country(id: 36, name: 'Colombia'),
  Country(id: 37, name: 'Comoros'),
  Country(id: 38, name: 'Congo (Republic)'),
  Country(id: 39, name: 'Congo (Democratic Republic)'),
  Country(id: 40, name: 'Costa Rica'),
  Country(id: 41, name: "Côte d'Ivoire"),
  Country(id: 42, name: 'Croatia'),
  Country(id: 43, name: 'Cuba'),
  Country(id: 44, name: 'Cyprus'),
  Country(id: 45, name: 'Czechia'),
  Country(id: 46, name: 'Denmark'),
  Country(id: 47, name: 'Djibouti'),
  Country(id: 48, name: 'Dominica'),
  Country(id: 49, name: 'Dominican Republic'),
  Country(id: 50, name: 'Ecuador'),
  Country(id: 51, name: 'Egypt'),
  Country(id: 52, name: 'El Salvador'),
  Country(id: 53, name: 'Equatorial Guinea'),
  Country(id: 54, name: 'Eritrea'),
  Country(id: 55, name: 'Estonia'),
  Country(id: 56, name: 'Eswatini'),
  Country(id: 57, name: 'Ethiopia'),
  Country(id: 58, name: 'Fiji'),
  Country(id: 59, name: 'Finland'),
  Country(id: 60, name: 'France'),
  Country(id: 61, name: 'Gabon'),
  Country(id: 62, name: 'Gambia'),
  Country(id: 63, name: 'Georgia'),
  Country(id: 64, name: 'Germany'),
  Country(id: 65, name: 'Ghana'),
  Country(id: 66, name: 'Greece'),
  Country(id: 67, name: 'Grenada'),
  Country(id: 68, name: 'Guatemala'),
  Country(id: 69, name: 'Guinea'),
  Country(id: 70, name: 'Guinea-Bissau'),
  Country(id: 71, name: 'Guyana'),
  Country(id: 72, name: 'Haiti'),
  Country(id: 73, name: 'Honduras'),
  Country(id: 74, name: 'Hungary'),
  Country(id: 75, name: 'Iceland'),
  Country(id: 76, name: 'India'),
  Country(id: 77, name: 'Indonesia'),
  Country(id: 78, name: 'Iran'),
  Country(id: 79, name: 'Iraq'),
  Country(id: 80, name: 'Ireland'),
  Country(id: 81, name: 'Israel'),
  Country(id: 82, name: 'Italy'),
  Country(id: 83, name: 'Jamaica'),
  Country(id: 84, name: 'Japan'),
  Country(id: 85, name: 'Jordan'),
  Country(id: 86, name: 'Kazakhstan'),
  Country(id: 87, name: 'Kenya'),
  Country(id: 88, name: 'Kiribati'),
  Country(id: 89, name: 'Kosovo'),
  Country(id: 90, name: 'Kuwait'),
  Country(id: 91, name: 'Kyrgyzstan'),
  Country(id: 92, name: 'Laos'),
  Country(id: 93, name: 'Latvia'),
  Country(id: 94, name: 'Lebanon'),
  Country(id: 95, name: 'Lesotho'),
  Country(id: 96, name: 'Liberia'),
  Country(id: 97, name: 'Libya'),
  Country(id: 98, name: 'Liechtenstein'),
  Country(id: 99, name: 'Lithuania'),
  Country(id: 100, name: 'Luxembourg'),
  Country(id: 101, name: 'Madagascar'),
  Country(id: 102, name: 'Malawi'),
  Country(id: 103, name: 'Malaysia'),
  Country(id: 104, name: 'Maldives'),
  Country(id: 105, name: 'Mali'),
  Country(id: 106, name: 'Malta'),
  Country(id: 107, name: 'Marshall Islands'),
  Country(id: 108, name: 'Mauritania'),
  Country(id: 109, name: 'Mauritius'),
  Country(id: 110, name: 'Mexico'),
  Country(id: 111, name: 'Micronesia'),
  Country(id: 112, name: 'Moldova'),
  Country(id: 113, name: 'Monaco'),
  Country(id: 114, name: 'Mongolia'),
  Country(id: 115, name: 'Montenegro'),
  Country(id: 116, name: 'Morocco'),
  Country(id: 117, name: 'Mozambique'),
  Country(id: 118, name: 'Myanmar'),
  Country(id: 119, name: 'Namibia'),
  Country(id: 120, name: 'Nauru'),
  Country(id: 121, name: 'Nepal'),
  Country(id: 122, name: 'Netherlands'),
  Country(id: 123, name: 'New Zealand'),
  Country(id: 124, name: 'Nicaragua'),
  Country(id: 125, name: 'Niger'),
  Country(id: 126, name: 'Nigeria'),
  Country(id: 127, name: 'North Korea'),
  Country(id: 128, name: 'North Macedonia'),
  Country(id: 129, name: 'Norway'),
  Country(id: 130, name: 'Oman'),
  Country(id: 131, name: 'Pakistan'),
  Country(id: 132, name: 'Palau'),
  Country(id: 133, name: 'Palestine'),
  Country(id: 134, name: 'Panama'),
  Country(id: 135, name: 'Papua New Guinea'),
  Country(id: 136, name: 'Paraguay'),
  Country(id: 137, name: 'Peru'),
  Country(id: 138, name: 'Philippines'),
  Country(id: 139, name: 'Poland'),
  Country(id: 140, name: 'Portugal'),
  Country(id: 141, name: 'Qatar'),
  Country(id: 142, name: 'Romania'),
  Country(id: 143, name: 'Russia'),
  Country(id: 144, name: 'Rwanda'),
  Country(id: 145, name: 'Saint Kitts and Nevis'),
  Country(id: 146, name: 'Saint Lucia'),
  Country(id: 147, name: 'Saint Vincent and the Grenadines'),
  Country(id: 148, name: 'Samoa'),
  Country(id: 149, name: 'San Marino'),
  Country(id: 150, name: 'Sao Tome and Principe'),
  Country(id: 151, name: 'Saudi Arabia'),
  Country(id: 152, name: 'Senegal'),
  Country(id: 153, name: 'Serbia'),
  Country(id: 154, name: 'Seychelles'),
  Country(id: 155, name: 'Sierra Leone'),
  Country(id: 156, name: 'Singapore'),
  Country(id: 157, name: 'Slovakia'),
  Country(id: 158, name: 'Slovenia'),
  Country(id: 159, name: 'Solomon Islands'),
  Country(id: 160, name: 'Somalia'),
  Country(id: 161, name: 'South Africa'),
  Country(id: 162, name: 'South Korea'),
  Country(id: 163, name: 'South Sudan'),
  Country(id: 164, name: 'Spain'),
  Country(id: 165, name: 'Sri Lanka'),
  Country(id: 166, name: 'Sudan'),
  Country(id: 167, name: 'Suriname'),
  Country(id: 168, name: 'Sweden'),
  Country(id: 169, name: 'Switzerland'),
  Country(id: 170, name: 'Syria'),
  Country(id: 171, name: 'Taiwan'),
  Country(id: 172, name: 'Tajikistan'),
  Country(id: 173, name: 'Tanzania'),
  Country(id: 174, name: 'Thailand'),
  Country(id: 175, name: 'Timor-Leste'),
  Country(id: 176, name: 'Togo'),
  Country(id: 177, name: 'Tonga'),
  Country(id: 178, name: 'Trinidad and Tobago'),
  Country(id: 179, name: 'Tunisia'),
  Country(id: 180, name: 'Turkey'),
  Country(id: 181, name: 'Turkmenistan'),
  Country(id: 182, name: 'Tuvalu'),
  Country(id: 183, name: 'Uganda'),
  Country(id: 184, name: 'Ukraine'),
  Country(id: 185, name: 'United Arab Emirates'),
  Country(id: 186, name: 'United Kingdom'),
  Country(id: 187, name: 'United States of America'),
  Country(id: 188, name: 'Uruguay'),
  Country(id: 189, name: 'Uzbekistan'),
  Country(id: 190, name: 'Vanuatu'),
  Country(id: 191, name: 'Vatican City'),
  Country(id: 192, name: 'Venezuela'),
  Country(id: 193, name: 'Vietnam'),
  Country(id: 194, name: 'Yemen'),
  Country(id: 195, name: 'Zambia'),
  Country(id: 196, name: 'Zimbabwe'),
];
