import 'asset.dart';

List<AssetDTO> sampleAssetDTOs() => [
  AssetDTO(
    assetId: "1",
    originalPrice: "0,00",
    initialDepreciationValue: "0,00",
    initialDepreciationPeriod: "0",
    liquidationValue: "0,00",
    assetModel: "2113-Phương tiện vận tải, truyền dẫn",
    depreciationMethod: "Đường thẳng",
    depreciationPeriods: "60",
    assetAccount: "2113",
    depreciationAccount: "2141",
    costAccount: "6274",
    assetGroup: "1 - Nhà cửa, công trình gắn liền với đất",
    entryDate: "25/07/2025",
    usageDate: "25/07/2025",
    project: "001 - 99",
    fundingSource: "Vốn đầu tư",
    symbol: "",
    symbolNumber: "",
    capacity: "",
    countryOfOrigin: "Việt Nam",
    yearOfManufacture: "2025",
    reasonForIncrease: "Dự án",
    status: "Đang sử dụng",
    quantity: "1",
    unit: "1",
    note: "",
    initialUnitCreated: true,
    initialUsageUnit: "Công đoàn",
    currentUnit: "",
  ),
]; 